version: '3.6'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: wialon
      POSTGRES_USER: wialon
      POSTGRES_DB: wialon

    volumes:
      - ./dumps/init.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - wialonNetwork
  api:
    build:
      args:
        user: api
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: wialon-api
    container_name: wialon-api
    logging:
      options:
        max-size: 10m
    depends_on:
      - db
    command: sh -c "/wait && yarn install --frozen-lockfile && yarn start:prod"
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - '3333:3333'
    volumes:
      - ./:/usr/src/app
    networks:
      - wialonNetwork
volumes:
  pgdata:
    driver: local

networks:
  wialonNetwork:
    driver: bridge
